apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandy-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandy-app
  template:
    metadata:
      labels:
        app: sandy-app
    spec:
      containers:
      - name: sandy-container
        image: sandeep7981/sandy-website:v1
        ports:
        - containerPort: 80
